config/routes.rb
Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  get 'favorites/update'

  root to: 'posts#index'
  get '/posts/favorites', to: 'posts#favorites', as: 'favorites'

  resources :posts do
    member do
      put "like" => "posts#vote"
    end
    # post 'comments', to: 'comments#create'
    resources :comments, only: [:create, :destroy]
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :body, presence: true, allow_blank: false
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_votable
  
  belongs_to :user
  has_many :comments, dependent: :destroy

  has_attached_file :image, styles: { medium: "600x500#", small: "350x250>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_voter
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :favorites
  has_many :posts 
  has_many :comments, dependent: :destroy

  def username
    return email.split('@')[0].capitalize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  def favorite_text
    return @favorite_exists ? "UnFavorite" : "Favorite"
  end

  helper_method :favorite_text

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :set_post
  before_action :authenticate_user!

  def create
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user
    @comment.save
  end

  def destroy
    @comment = @post.comments.find(params[:id])
    @comment_id = @comment.id
    @comment.destroy
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :post_id)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def update
    favorite = Favorite.where(post: Post.find(params[:post]), user: current_user)
    if favorite == []
      # Create the favorite
      Favorite.create(post: Post.find(params[:post]), user: current_user)
      @favorite_exists = true
    else
      #Delete the favorite(s)
      favorite.destroy_all
      @favorite_exists = false
    end

    respond_to do |format|
      format.html {}
      format.js {}
    end

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :vote]
  before_action :authenticate_user!, except: [:index, :show, :vote]
  respond_to :js, :json, :html

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @favorite_exists = Favorite.where(post: @post, user: current_user) == [] ? false : true
    @comment = Comment.new
    @comments = @post.comments.order("created_at DESC")
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def vote 
    if !current_user.liked? @post
      @post.liked_by current_user
    elsif current_user.liked? @post
      @post.unliked_by current_user
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div id="comment-<%= comment.id %>">
  [ <%= comment.created_at.strftime("%I:%M %p") %> ] 
  <%= comment.user.username %>
  <% if current_user && current_user == comment.user || current_user.admin? %>
    <%= link_to "Delete", post_comment_path(@post, comment), method: :delete, remote: true, style: 'float: right' %>
    <hr />
  <% end %>
  <%= comment.body %>
  <br />
  <br />
</div>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/create.js.erb
$('#comment_pane').prepend("<%= j render @comment %>");
$('#comment_body').val('');

app/views/comments/destroy.js.erb
$('#comment-<%= @comment.id %>').html('');

app/views/favorites/update.js.erb
$('#favorite_link').text("<%= favorite_text %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
   <title>Mark37</title>
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
   <meta content="IE=edge, chrome=1" http-equiv="X-UA-Compatible">
   <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
   <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script> -->
   <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>
    
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>

  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :image %>
  <%= f.input :title %>
  <%= f.input :body %>

  <%= f.button :submit %>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/favorites.html.erb
<h1>Your Favorite Posts </h1>
<% current_user.favorites.each do |favorite| %>
   you favorited this post: <%= link_to favorite.post.title, favorite.post %>
<% end %>

app/views/posts/index.html.erb
<div class="layout">
  <%= render 'shared/header' %>
  <div class="wrap">
  
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />

    <!-- <p id="notice"><%= notice %></p> -->

    <% if user_signed_in? %>
      Hello, <%= current_user.name %><br />
      How are you TODAY? :D
    <% else %>
      Welcome Everyone :D
    <% end %>
    
    <% if current_user.try(:admin?) %>
      <p>You Are Admin</p>
    <% end %>

    

    <h1>Posts</h1>
    <% @posts.each do |post| %>
      <%= link_to (image_tag post.image.url(:small)), post %>
      <h2><%= link_to post.title, post %></h2>
      <p><%= post.user.name %></p>
      <p><%= post.body %></p>
      <%= pluralize(post.comments.count, "Comment") %>
      <%= post.get_upvotes.size %> Likes
      <% if current_user.try(:admin?) %>
        <%= link_to 'Edit', edit_post_path(post) %>
        <%= link_to "Delete", post_path(post), method: :delete, data: {confirm: "Are you sure?"}%>
      <% end %>
      
    <% end %>


    <br>

    <div class="index_box">

    </div>

  </div><!--./wrap -->
</div><!-- ./layout -->

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<%= image_tag @post.image.url(:medium) %>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
  <%= link_to like_post_path(@post), class: "like-btn", method: :put, remote: :true  do %>
    <div><span><p>LIKE</p></span></div>
    <span class="likes-count"><%= @post.get_upvotes.size %></span>
  <% end %>
</p>

<%= link_to favorite_text, favorites_update_path(post: @post), id:'favorite_link', remote: true %>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

<!-- Comment Input Form -->
<% if current_user %>
  <%= form_with model: [@post, @comment] do |f| %>
    <%= f.text_field :body, id: "comment_body" %>
    <%= f.submit "Comment" %>
  <% end %>
<% else %>
  <p>You need to <%= link_to "Login", new_user_session_path %> before you can comment.</p>
<% end %>
<div id="comment_pane">
  <% @comments.each do |comment| %>
    <%= render 'comments/comment', comment: comment %>
  <% end %>
</div>

app/views/posts/vote.js.erb
<% if current_user.liked? @post %>
  $('.like-btn').addClass('liked');
<% else %>
  $('.like-btn').removeClass('liked'); 
<% end %>
$('.likes-count').html("<%= @post.get_upvotes.size %>")

app/views/shared/_header.html.erb
<header class="site-header">
  <div class="site-toolbar">
    <div class="container"></div>
  </div>
  <div class="navbar-container">
    <div class="container">
      <nav class="site-navbar">
        <div class="box-left">
          <a href="#" class="site-logo navbar-item nav_logo">Fromco</a>
        </div>
        <div class="box-right">
          <ul id="primary-menu" class="main-menu navbar-nav">
            <li id="menu-item-1811" class="menu-item current-menu-item"><a href="#">Home</a></li>
            <li id="menu-item-1770" class="menu-item menu-item-has-children">
              <a href="#" aria-haspopup="true" aria-expanded="false">About Us</a>
              <ul class="sub-menu">
                <li id="menu-item-1799" class="menu-item"><a href="#">Studio</a></li>
                <li id="menu-item-1800" class="menu-item"><a href="#">Team</a></li>
                <li id="menu-item-1771" class="menu-item"><a href="#">Services</a></li>
              </ul>
            </li>

            <li id="menu-item-1774" class="menu-item menu-item-has-children">
              <a href="#" aria-haspopup="true" aria-expanded="false">Level 1</a>
              <ul class="sub-menu">
                <li id="menu-item-1775" class="menu-item menu-item-has-children">
                  <a href="#" aria-haspopup="true" aria-expanded="false">Level 2</a>
                  <ul class="sub-menu">
                    <li id="menu-item-1776" class="menu-item menu-item-has-children">
                      <a href="#">Level 3</a>
                      <ul class="sub-menu">
                        <li id="menu-item-1776" class="menu-item">
                          <a href="#" aria-haspopup="true" aria-expanded="false">Level 4</a>
                        </li>
                        <li id="menu-item-1801" class="menu-item"><a href="#">Level 4a</a></li>
                        <li id="menu-item-1802" class="menu-item"><a href="#">Level 4b</a></li>
                      </ul>
                    </li>
                    <li id="menu-item-1801" class="menu-item"><a href="#">Level 3a</a></li>
                    <li id="menu-item-1802" class="menu-item"><a href="#">Level 3b</a></li>
                  </ul>
                </li>
                <li id="menu-item-1803" class="menu-item"><a href="#">Level 2a</a></li>
                <li id="menu-item-1804" class="menu-item"><a href="#">Level 2b</a></li>
              </ul>
            </li>
            <!-- <li id="menu-item-1777" class="menu-item"><a href="#">Our Work</a></li>
            <li id="menu-item-1805" class="menu-item"><a href="#">The News</a></li>
            <li id="menu-item-1806" class="menu-item"><a href="#">Contact Us</a></li> -->
            <% if user_signed_in? %>
             <li id="menu-item-1777" class="menu-item"><%= link_to "Add New Post", new_post_path %></li>
             <li id="menu-item-1805" class="menu-item"><%= link_to "My Favorites", favorites_path %></li>
             <li id="menu-item-1805" class="menu-item"><a href="#"><%= link_to('Logout', destroy_user_session_path, method: :delete) %></a></li>
            <% else %>
             <li id="menu-item-1806" class="menu-item"><li><%= link_to "Sign In", new_user_session_path %></li></li>
             <li id="menu-item-1806" class="menu-item"><%= link_to "Sign Up", new_user_registration_path, class: "button" %></li>
            <% end %>
          </ul>
          <div class="navbar-item">
            <a class="responsive-nav">
              <span class="line"></span>
              <span class="line"></span>
              <span class="line"></span>
            </a>
          </div>
        </div>
      </nav>
    </div>
  </div>
</header>
<!-- overlay -->
<div class="site-overlay"></div>